{ config, pkgs, ... }:

{
  imports = [
    # Include the results of the hardware scan.
    # Regenerated by the installer. Do not carry the July file forward.
    ./hardware-configuration.nix
  ];

  boot.kernelParams = [ "amd_pstate=active" "amdgpu.ppfeaturemask=0xffffffff" ];

  # amdgpu in initrd for early KMS. Lives here, not in
  # hardware-configuration.nix, so it survives regeneration.
  boot.initrd.kernelModules = [ "amdgpu" ];

  boot.kernel.sysctl = {
    "vm.max_map_count" = 2147483642;
    # Matched to CachyOS defaults: high swappiness is intentional with
    # large zram, page-cluster 0 avoids readahead penalty on zram.
    "vm.swappiness" = 150;
    "vm.page-cluster" = 0;
    "vm.vfs_cache_pressure" = 50;
    "net.core.default_qdisc" = "fq";
    "net.ipv4.tcp_congestion_control" = "bbr";
  };

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.systemd-boot.configurationLimit = 10;

  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 14d";
  };

  nix.settings = {
    experimental-features = [
      "nix-command"
      "flakes"
    ];
    substituters = [
      "https://cache.nixos.org"
      "https://attic.xuyh0120.win/lantian"
    ];
    trusted-public-keys = [
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
      "lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc="
    ];
  };

  networking.hostName = "nixos";

  # NetworkManager with the OpenVPN plugin for the manual NordVPN
  # profiles. Import the .ovpn files in GNOME Settings after install,
  # using the service credentials from the Nord Account dashboard.
  networking.networkmanager = {
    enable = true;
    plugins = with pkgs; [ networkmanager-openvpn ];
  };

  # Set your time zone.
  time.timeZone = "Europe/Berlin";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "de_DE.UTF-8";
    LC_IDENTIFICATION = "de_DE.UTF-8";
    LC_MEASUREMENT = "de_DE.UTF-8";
    LC_MONETARY = "de_DE.UTF-8";
    LC_NAME = "de_DE.UTF-8";
    LC_NUMERIC = "de_DE.UTF-8";
    LC_PAPER = "de_DE.UTF-8";
    LC_TELEPHONE = "de_DE.UTF-8";
    LC_TIME = "de_DE.UTF-8";
  };

  # Enable the X11 windowing system (XWayland and keymap handling).
  services.xserver.enable = true;

  # GNOME Desktop Environment.
  services.displayManager.gdm.enable = true;
  services.desktopManager.gnome.enable = true;
  # Note: GDM on Wayland uses the first enumerated DisplayPort output,
  # not the primary flag. Same cable-order fix as on Bazzite applies.

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  zramSwap = {
    enable = true;
    algorithm = "zstd";
    # Matched to CachyOS: zram sized to RAM, preferred over disk swap.
    memoryPercent = 100;
    priority = 100;
  };

  # AMD graphics. The 9070 XT needs nothing beyond Mesa, which
  # hardware.graphics provides. 32-bit is required for Proton titles.
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Enable sound with pipewire.
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Define a user account. Don't forget to set a password with 'passwd'.
  users.users."ssow" = {
    isNormalUser = true;
    description = "Sada Sow";
    extraGroups = [
      "networkmanager"
      "wheel"
      "libvirtd"
      "kvm"
    ];
    packages = with pkgs; [
      thunderbird
    ];
  };

  users.defaultUserShell = pkgs.zsh;

  programs.neovim = {
    enable = true;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;
  };

  programs.nix-ld.enable = true;

  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
  ];

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  programs.steam = {
    enable = true;
    remotePlay.openFirewall = true;
    dedicatedServer.openFirewall = false;
    gamescopeSession.enable = true;
  };

  programs.gamemode.enable = false;

  environment.systemPackages = with pkgs; [
    # Editors and dev
    vim
    git
    gcc
    python3
    vscode
    zed-editor
    obsidian
    # LSP servers on PATH, Mason stays disabled in LazyVim
    nil
    nixfmt
    statix
    lua-language-server
    pyright

    # Shell and CLI
    wget
    curl
    fzf
    tree
    ripgrep
    fd
    bat
    file
    tealdeer
    fastfetch
    wl-clipboard
    btop

    # System and backup
    restic
    chezmoi
    deja-dup
    dnsmasq
    fuse2
    gearlever

    # Desktop apps
    brave
    ghostty
    alacritty
    discord
    telegram-desktop
    zoom-us
    localsend

    # GNOME
    gnome-tweaks
    gnome-extension-manager

    # Gaming and graphics
    mangohud
    mangojuice
    vkbasalt
    gamescope
    protonplus
    protonup-qt
    lact

    # Networking and lab
    gns3-gui
    gns3-server
    mullvad-vpn

    # Zsh
    oh-my-zsh
  ];

  services.lact.enable = true;

  programs.localsend.enable = true;

  system.userActivationScripts.zshrc = "touch .zshrc";

  programs.zsh = {
    enable = true;
    enableCompletion = true;
    autosuggestions.enable = true;
    syntaxHighlighting.enable = true;
    ohMyZsh = {
      enable = true;
      plugins = [ "git" ];
      theme = "robbyrussell";
    };
  };

  programs._1password.enable = true;
  programs._1password-gui = {
    enable = true;
    polkitPolicyOwners = [ "ssow" ];
  };

  services.mullvad-vpn.enable = true;
  services.mullvad-vpn.gui.enable = true;
  # services.mullvad-vpn.package = pkgs.mullvad-vpn;

  # Virtualisation. OVMF and swtpm are required for the UEFI guests
  # (Whonix, hl-soc, KaliOSCP). Domains and networks themselves are
  # imperative: restore images from B2, chattr +C the images subvolume
  # first, then virsh net-define before virsh define.
  virtualisation.libvirtd = {
    enable = true;
    qemu = {
      swtpm.enable = true;
    };
  };
  virtualisation.spiceUSBRedirection.enable = true;
  programs.virt-manager.enable = true;

  programs.appimage = {
    enable = true;
    binfmt = true;
  };

  programs.dconf.enable = true;
  programs.dconf.profiles.user.databases = [
    {
      settings = {
        "org/gnome/shell" = {
          disable-extension-version-validation = true;
        };
      };
    }
  ];

  # Declarative restic to B2, replacing the hand-rolled timer from
  # CachyOS. Fill in the environment file with B2 credentials and the
  # repo password, then uncomment.
  # services.restic.backups.b2 = {
  #   repository = "b2:cachyos-backup-ss:/nixos";
  #   environmentFile = "/etc/restic/env";
  #   paths = [ "/home/ssow" "/etc" "/var/lib/libvirt/images" ];
  #   timerConfig = {
  #     OnCalendar = "daily";
  #     Persistent = true;
  #   };
  #   pruneOpts = [ "--keep-daily 7" "--keep-weekly 4" "--keep-monthly 6" ];
  # };

  system.stateVersion = "26.05"; # Did you read the comment?

}
